from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

userName = os.environ['roshanchittoor_eu4FN9']
accessKey = os.environ['R11Vpxwkye3iYPty1ZfT']
localIdentifier = os.environ['BROWSERSTACK_LOCAL_IDENTIFIER']
buildName = os.environ['BROWSERSTACK_BUILD_NAME']
projectName = os.environ['BROWSERSTACK_PROJECT_NAME']

desired_cap = 
{
 'os': 'Windows',
 'os_version': '10',
 'browser': 'Chrome',
 'browser_version': 'latest',
 'browserstack.local': 'true',
 'browserstack.localIdentifier': localIdentifier,
 'build': buildName,
 'project': projectName
}

driver = webdriver.Remote(
    command_executor='https://'+userName+':'+accessKey+'@hub-cloud.browserstack.com/wd/hub',
    desired_capabilities=desired_cap)
driver.get("http://localhost:8099") # HTTP Server should be running on 8099 port of GitHub runner
print(driver.title)
driver.quit()

